export type InventoryRow = {
  title: string | null;
  description: string | null;
  vendor: string | null;
  category: string | null;
  status: string | null;
  type: string | null;
  tags: string | null;
  published: boolean | null;
  option1_name: string | null;
  option1_value: string | null;
  option2_name: string | null;
  option2_value: string | null;
  variant_sku: string | null;
  variant_grams: number | null;
  variant_inventory_tracker: string | null;
  variant_inventory_policy: string | null;
  variant_fulfillment_service: string | null;
  variant_price: number | null;
  variant_compare_at_price: number | null;
  variant_requires_shipping: boolean | null;
  variant_taxable: boolean | null;
  variant_barcode: string | null;
  image_src: string | null;
  variant_image: string | null;
  variant_weight_unit: string | null;
  cost_per_item: number | null;
};