// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffdidzefycdlnojrwbwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmZGlkemVmeWNkbG5vanJ3Ynd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQyMDQ3ODQsImV4cCI6MjA0OTc4MDc4NH0.DMgjxLxnOZPewEffFtRZfweZtPT7-JDJnxyFYUVkDkU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);