// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fuzfnljfbqobocztajjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1emZubGpmYnFvYm9jenRhampiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4OTAxOTksImV4cCI6MjA2MTQ2NjE5OX0.5fzuKX0ki5zOQxYDqPqykhgWkarCqDeYUEt2OO2gK3g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});